version: '3.8'
services:
  server1:
    build:
      context: ./server1
      dockerfile: ./Dockerfile
    container_name: server1
    restart: always
  server2:
    build:
      context: ./server2
      dockerfile: ./Dockerfile
    container_name: server2
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/assets:/var/www/html/assets
    depends_on:
      - server1
      - server2
    restart: always
